GRANT CONNECT to MASTER_CONTACT;

GRANT UNLIMITED TABLESPACE TO MASTER_CONTACT;

GRANT 
CREATE TABLE
,CREATE INDEXTYPE
,CREATE VIEW
,CREATE TYPE 
,CREATE SEQUENCE 
,CREATE PROCEDURE
,CREATE TRIGGER 
,CREATE PUBLIC SYNONYM
,CREATE JOB
,CREATE MATERIALIZED VIEW
,CREATE ANY CONTEXT
,DROP ANY CONTEXT
to MASTER_CONTACT;

GRANT EXECUTE ANY PROCEDURE TO MASTER_CONTACT;

GRANT EXECUTE ON SYS.DBMS_PIPE TO MASTER_CONTACT;
GRANT EXECUTE ON SYS.DBMS_ALERT TO MASTER_CONTACT;
GRANT EXECUTE ON SYS.DBMS_SESSION TO MASTER_CONTACT;
GRANT EXECUTE ON SYS.DBMS_SCHEDULER TO MASTER_CONTACT;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO MASTER_CONTACT;
GRANT EXECUTE ON SYS.UTL_FILE TO MASTER_CONTACT;
GRANT EXECUTE ON SYS.UTL_RAW TO MASTER_CONTACT;

