--select * from dba_data_files; -- find location of database files

-- Create tablespace (for windows)
CREATE TABLESPACE TBS_PG_DATA DATAFILE 'C:\app\admin\oradata\orcl\TBS_RP_DATA.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 10G EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
CREATE TABLESPACE TBS_PG_IDX DATAFILE 'C:\app\admin\oradata\orcl\TBS_RP_IDX.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 10G EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

 

