CREATE TABLE USR
(
ID							NUMBER(38, 0) 	NOT NULL ,
REF_ID						VARCHAR2(50) 	NOT NULL ,
PSWD						VARCHAR2(2000) 	NOT NULL ,
EMAIL						VARCHAR2(2000) ,
USR_ROLE					VARCHAR2(50),
CNTCT_NUMBER				VARCHAR2(50),
IS_ACTIVE                 	VARCHAR2(50) NOT NULL,
ADDRESS                     VARCHAR2(50),
CRT_BY              		VARCHAR2(50) DEFAULT USER ,
CRT_TS              		TIMESTAMP (6) DEFAULT SYSTIMESTAMP ,
UPD_BY						VARCHAR2(50),
UPD_TS						TIMESTAMP (6)
)TABLESPACE T_TXN_DATA;


ALTER TABLE USR ADD CONSTRAINT M_USR_PK PRIMARY KEY(ID); 
ALTER TABLE USR ADD CONSTRAINT M_USR_UNIQ UNIQUE(REF_ID);
ALTER TABLE USR ADD CONSTRAINT M_USR_EMAIL_UNIQ UNIQUE(EMAIL);


CREATE TABLE CONTACT		
(
	ID				NUMBER(38) NOT NULL , 
	USR_ID          NUMBER(38) NOT NULL , 
	NAME			VARCHAR2(100),
	PHONE_NO		VARCHAR2(100),
	EMAIL			VARCHAR2(100),
	ADDRESS         VARCHAR2(50),
	IMAGES          VARCHAR2(1000),
	DESCR           VARCHAR2(500),
	CRT_TS			TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,		
	CRT_BY          VARCHAR2(50) DEFAULT USER ,
	UPD_TS			TIMESTAMP (6) ,
	UPD_BY          VARCHAR2(50),
	DEL_TS			TIMESTAMP(6),
	DEL_BY          VARCHAR2(50)
)TABLESPACE T_TXN_DATA;

ALTER TABLE CONTACT ADD CONSTRAINT M_CNT_PK PRIMARY KEY(ID); 
ALTER TABLE CONTACT ADD CONSTRAINT M_CNT_M_USR_FK FOREIGN KEY (USR_ID) REFERENCES USR(ID);
ALTER TABLE CONTACT ADD CONSTRAINT M_CNT_UNIQ UNIQUE  (EMAIL);



